version: '3'

services:
  teamsdns:
    image: talkincode/justdoit:latest
    container_name: justdoit
    command: ["node", "src/index.js"]
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"